### ISSUE TITLE
如何在该项目配置终端呢

### ISSUE THREAD

**Issue by gaoshengqing21** [opensumi/codeblitz-sample#3]
如何在该项目配置终端呢？可以进行npm安装和启动

**Comment by AhkunTa** [comment]
codeblitz  为基于Opensumi 的纯前端的IDE方案 暂时无法集成终端

正在基于 WebContainer 做终端能力的适配 
可以实现类似于 [stackblitz](https://stackblitz.com/) 的能力

但 WebContainer 也只是模拟Node端实现 如果想使用完整终端能力 可以使用 Opensumi

**Comment by gaoshengqing21** [comment]
该如何配置自己的项目到这个IDE中呢？有实例文档吗

**Comment by wangxiaozhuzhu** [comment]
> codeblitz 为基于Opensumi 的纯前端的IDE方案 暂时无法集成终端
> 
> 正在基于 WebContainer 做终端能力的适配 可以实现类似于 [stackblitz](https://stackblitz.com/) 的能力
> 
> 但 WebContainer 也只是模拟Node端实现 如果想使用完整终端能力 可以使用 Opensumi

这个终端适配大概什么时候可以使用？
